# Update this file:
#   pre-commit autoupdate
repos:
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.1
  - hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
        types:
          - python
      - id: trailing-whitespace
        types:
          - python
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - id: black
        types:
          - python
    repo: https://github.com/psf/black
    rev: 23.3.0
  - hooks:
      - id: flake8
        args:
          - --max-line-length=89
    repo: https://github.com/pycqa/flake8
    rev: 6.0.0
  - hooks:
    - id: blacken-docs
      additional_dependencies:
        - black==22.3.0
    repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
  - hooks:
      - id: pyupgrade
        args:
          - --py36-plus
    repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
  - hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args:
          - -f
          - requirements.txt
          - --without-hashes
          - -o
          - requirements.txt
    repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
  - hooks:
      - id: pytest
        always_run: true
        entry: poetry run pytest -v
        language: python
        name: pytest
        pass_filenames: false
        types:
          - python
    repo: local
